Repository yuurmj/public-toilet-datamap, pull requests merged in 2025-09, with the labels that each got.

#6 docs: 프로젝트 개요, 주요기능 추가
  README.md
  image.png
Labels: 🐤정아란

#8 [Visualization] 시각화 코드 구현
  app/pages/app.py
  data/population_mock.csv
  data/toilets_mock.csv
  data/visitors_mock.csv
Labels: 🚽FEATURE, 🐤정아란

#10 [Data] 남구 CSV 데이터 및 전처리 결과 추가
  .gitignore
  data/processed/toilets_namgu_cleaned.csv
  data/raw/.gitkeep
  data/raw/toilets_namgu.csv
  scripts/clean_data.py
Labels: 🚽FEATURE, 🐰정유림
